# Coding Temple's Data Analytics Program  
---
# Advanced Python - Intro to `numpy`
---



## Part 1: Working with `numpy`


### 1.1 Importing `numpy`

We've already used the `numpy` package by importing it and assigning it the standard alias of `np`. Do this again in the following cell - the more you practice typing these lines of code, the easier it will be to remember.

In [2]:
# Import numpy and assign it the standard alias
# YOUR CODE HERE
import numpy as np

### 1.1 Solution - Run this cell to check your answer in 1.1. Please do not edit the values in this cell!

In [3]:
# DO NOT EDIT THIS CELL
assert np.__name__ == 'numpy', 'Make sure that you have properly imported numpy and aliased it as np!'

### 1.2 Generate random numbers

Create a `(5,3)` `numpy` array of random integer values between 0 and 100.

Use the the `random()` method in numpy to generate these integers. Name your new variable `myarray`. You should also print the array to check it's dimensions and values.

In [7]:
# Generate your random numbers
np.random.seed(1) #Seed generated for reproducibility

#YOUR CODE HERE
myarray=np.random.randint(0,1e2, (5,3))
# Print out the array
myarray

array([[37, 12, 72],
       [ 9, 75,  5],
       [79, 64, 16],
       [ 1, 76, 71],
       [ 6, 25, 50]])

### 1.2 Solution - Run the following cell to check your answer.

In [8]:
#DO NOT EDIT THIS CELL

#Verify the array was created with the correct name and has the proper shape
assert myarray.shape == (5,3), 'Make sure you create an array with the proper shape!'

### 1.3 Calculate BMI 

Using the two lists provided, please calculate the BMI(body mass index) of each individual using NDArrays. Save the variable containing your results as `bmi`

The formula for BMI in pounds and inches can be defined as: $BMI= \frac{703 * weight} {(height)^2}$

In [15]:
height = [55, 120, 90, 100]
weight = [170, 180, 190, 200]

bmi=(np.round((703*(np.array(weight)))/((np.array(height))**2),2))
bmi

array([39.51,  8.79, 16.49, 14.06])

### 1.3 Solution: Run the following cell to check your answer.

In [16]:
assert 'bmi' in dir() , 'Make sure you have saved your results to the proper variable name!'
assert type(bmi) == np.ndarray, 'Make sure that you made the calculation using an NDArray for both height and weight!'

### 1.4 Create a function 

Create a function named `my_func` that will take in two parameters and will create a random matrix based off of those parameters. Extra: Have additional parameters taken in that allow the user to choose the shape and data type of the matrix.

In [62]:
def my_func(starting_range,range_end,shape: tuple=(5,5), data_type = "integer"):
    if data_type.lower() == "integer":
        Func_Array = np.random.randint(starting_range,range_end,shape)
        return Func_Array
    elif data_type.lower() == "float":
        Func_Array = np.round(np.random.uniform(starting_range,range_end,shape,),2)
        return Func_Array

Mypirate = my_func(3,5e4,(8,4),"float")
print(Mypirate)

[[49038.   34329.1  45997.6   3472.59]
 [26574.32 29206.24 19333.47 13065.23]
 [22467.43 27380.93 42296.62 40790.32]
 [13065.43 49102.83 46403.1  16785.61]
 [35229.   32457.78 10441.91 37224.34]
 [48885.96 20781.96  4580.64 13067.12]
 [11445.04 41572.55 26342.12  1637.88]
 [38042.88 21170.41  8852.94 35062.84]]


### 1.5 Array practice

Time for some more practice. Run each of these tasks in the separate code cell listed below:

1.  Return the first row
2.  Return the last column
3.  Return the third column values from the 4th and 5th rows
4.  Multiply every value in the array by 2
5.  Divide every value by 3
6.  Increase the values in the first row by 12
7. Calculate the mean of the first column
8. Calculate the median of the array _after_ removing the 2 smallest values in the array
9. Calculate the standard deviation of the first 3 rows
10. Return values greater than 25 in the second column
11. Return values less than 40 in the array

In [63]:
# 1. Return the first row:
print(Mypirate[0])

[49038.   34329.1  45997.6   3472.59]


In [64]:
# 2. Return the last column
print(Mypirate[:,-1])

[ 3472.59 13065.23 40790.32 16785.61 37224.34 13067.12  1637.88 35062.84]


In [65]:
# 3. Return the third column values from the 4th and 5th rows
print(Mypirate[3:5,2])


[46403.1  10441.91]


In [66]:
# 4. Multiply every value in the array by 2
print(Mypirate*2)

[[98076.   68658.2  91995.2   6945.18]
 [53148.64 58412.48 38666.94 26130.46]
 [44934.86 54761.86 84593.24 81580.64]
 [26130.86 98205.66 92806.2  33571.22]
 [70458.   64915.56 20883.82 74448.68]
 [97771.92 41563.92  9161.28 26134.24]
 [22890.08 83145.1  52684.24  3275.76]
 [76085.76 42340.82 17705.88 70125.68]]


In [67]:
# 5. Divide every value by 3
print(np.round(Mypirate/3,2))

[[16346.   11443.03 15332.53  1157.53]
 [ 8858.11  9735.41  6444.49  4355.08]
 [ 7489.14  9126.98 14098.87 13596.77]
 [ 4355.14 16367.61 15467.7   5595.2 ]
 [11743.   10819.26  3480.64 12408.11]
 [16295.32  6927.32  1526.88  4355.71]
 [ 3815.01 13857.52  8780.71   545.96]
 [12680.96  7056.8   2950.98 11687.61]]


In [68]:
# 6. Increase the values in the first row by 12
print(Mypirate[0]+12)

[49050.   34341.1  46009.6   3484.59]


In [69]:
# 7. Calculate the mean of the first column
print(Mypirate[:,0].mean())

30593.5075


In [74]:
# 8. Calculate the median of the array after removing the 2 smallest values in the array
Mypiratecopy=np.sort(Mypirate[:,:])
print(np.median(Mypiratecopy[2:]))
print(np.median(Mypirate))



26861.525
26977.625


In [124]:
# 9. Calculate the standard deviation of the first 3 rows
# Generate a new array to work on
np.random.seed(2) # New seed for new array
Myarrgh = my_func(6,45)
Stdpirate =np.std(Myarrgh[0:3,:])
print(Stdpirate)
print(Myarrgh)

10.195859726161181
[[21 14 28 24 17]
 [13 40 37 17 27]
 [37 32 26 43  9]
 [44 10 44 39  9]
 [11 30 10 12 37]]


In [129]:
# 10. Return values in the second column greater than 25
mask = Myarrgh[:,1]> 25

print(Myarrgh[mask])


[[13 40 37 17 27]
 [37 32 26 43  9]
 [11 30 10 12 37]]


In [132]:
# 11. Return values < 40 in the array
mask = Myarrgh<40
print(Myarrgh[mask])

[21 14 28 24 17 13 37 17 27 37 32 26  9 10 39  9 11 30 10 12 37]


### Solution 1.5: Run the following cell to view the solution for each of the above tasks.

A new array will be generated to demonstrate the solution - the values will not be the same as your array. But the code for each task will still apply.

In [128]:
# DO NOT EDIT THIS CELL
# SOLUTION 1.3

# # SOLUTION: Make sure you have completed all of the above tasks
# # Generate your random numbers (NEW ARRAY)
# myarray = np.random.randint(100, size=(5, 3))
# print('The generated array: \n', myarray)
# print('\n')

# # 1. Return the first row:
# print('1. The first row: ', myarray[0])
# print('\n')

# # 2. Return the last column
# print('2. The last column: ', myarray[:,-1])
# print('\n')

# # 3. Return the third column values from the 4th and 5th rows
# print('3. The 3rd column, 4th & 5th rows: ', myarray[3:5,2])
# print('\n')

# # 4. Multiply every value in the array by 2
# # (operates on the original array)
# print('4. Multiply by 2: \n', myarray * 2)
# print('\n')

# # 5. Divide every value by 3
# # (operates on the original array)
# print('5. Divide by 3: \n', myarray / 3)
# print('\n')

# # 6. Increase the values in the first row by 12
# # (operates on the original array)
# print('6. Add 12 to the first row: \n', myarray[0,:] + 12)
# print('\n')

# # 7. Calculate the mean of the first column
# print('7. The mean of the 1st column: ', myarray[:,0].mean())
# print('\n')

# # 8. Calculate the median of the array after removing the 2 smallest values in the array
# # flatten and sort (axis=None does the flattening)
# myarray = np.sort(myarray, axis=None)
# # remove two smallest values
# myarray = myarray[2:]
# # calculate the median
# print('8. The median after removing the 2 smallest values: ', np.median(myarray))
# print('\n')

# # 9. Calculate the standard deviation of the first 3 rows
# # Generate new array first:
# myarray = np.random.randint(100, size=(5, 3))
# # Then calculate the std:
# print('9. The standard deviation is: ', np.std(myarray[0:3,:]))
# print('\n')

# 10. Return values in the second column greater than 25
# create a Boolean mask where values in the 2nd column > 25 are True
condition = myarray[:,1] > 25
# Apply the mask
print('10. All values in 2nd column > 25: \n', myarray[condition])
print('\n')

# 11. Return values < 40 in the array
# create another Boolean mask for values < 40
condition = myarray < 40
# apply the mask
print('11. All values < 40: \n', myarray[condition])

10. All values in 2nd column > 25: 
 [[65 94 60]
 [24 82 97]
 [ 2 92 98]
 [10 54 96]
 [82 86 70]]


11. All values < 40: 
 [24  2 10]
